project: world-fishing-827
bq_in: world-fishing-827.pipe_ais_sources_v20220628.normalized_consolidated
gcs_out: gs://gfw-int-ais-datalake-vessel-transmissions-v1/normalized_consolidated
schema_file: ./examples/assets/normalize-schema.json
date_range:
  - "2024-01-01"
  - "2024-01-31"
timestamp_field: timestamp
partition_fields: []
partition_time_granularity: hour
partition_prefix: event_
gcs_window_size: 3600
gcs_num_shards: 6
runner: DataflowRunner
dry_run: false
